### PR TITLE
RA-1592: Fix Appointment Scheduling UI template.

### PR DESCRIPTION
**Pull request by Akayeshmantha**
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now

Fix appointment scheduling UI fixes. 
Appointment blocks page width issue
service type text area width issue

This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Akayeshmantha did you just forget to claim the ticket?

**Comment by Akayeshmantha** [comment]
Hi @dkayiwa  
Always using the same issue as this one.

https://issues.openmrs.org/browse/RA-1592

**Comment by mozzy11** [comment]
cc @mks-d

**Comment by mozzy11** [comment]
Helo @mks-d  , can you please help us merge these changes , Thanks

**Pull request merged**
