### PR TITLE
Made changes to fix EMPT82

### PR DESCRIPTION
**Pull request by Parth59**
Hi Team,
This change is for fixing EMPT82. I have performed minor test runs to the best of my abilities.
@isears @sherrif10

Link to ticket
RA-1875 (https://issues.openmrs.org/browse/RA-1875)

Steps to reproduce :

1)Launch OpenMRS application using the URL: http://localhost:8080/openmrs

2)Provide following info and click login​Username​ as ​admin​ Password​ ​ as ​admin123 Location as ​Inpatient
3. Click System Administration.
4. Click Manage Accounts.
5. Select Add New Account.
6. Enter </script> <script>alert(`hello`)</script> as the family name, </script> <script>alert(`hello`)</script> as the given name, and select the gender as male.
7. Check Add Provider Account
8. Enter the Identifier as jdoe5 and select Clerk as the Provider Role.
9. Navigate back to the home page by selecting OpenMRS in the top left corner.
10. Select Find Patient Record and select John D Patient.
11. Select Request Appointment. Type in script and select the provider we just created, and enter Surgery as the service type. 

Before fix 
Beofre

After fix 

After_EMPT80
After_EMPT80_Part2

### CODE REVIEW

**Comment by brandones** [comment]
There are some very serious code quality issues here. But before I even get into it, it would be great if @isears could confirm that this is at least the right idea.

**Comment by isears** [comment]
@brandones I've been discussing this issue with @Parth59 as part of the GSoC security project. This bug in particular has been pretty tough, so ultimately any solution is going to come out a little hacky but I think you're right that we need to find an alternative.

One idea is to add an optional `htmlencoded` parameter to the openmrs rest endpoint that's returning the data so that the frontend can request pre-encoded data, which could then be safely included in the DOM. Let us know if you've got any suggestions!

**Comment by brandones** [comment]
@isears I actually don't have a problem with the approach, though I would prefer wrapping the logic in helper functions. I mean that there are fundamental semantic problems with the code here—specifically that for-in loop and its contents. Anyway, looking forward to see what y'all come up with.

**Comment by Parth59** [comment]
Hi Team,

As discussed in the last meeting, here's the priority matrix for the direction to tackle the issue:-

**Priority 1) Check for typeahead fix.** 
Am researching on this currently  https://github.com/angular-ui/bootstrap/issues/4073

**Priority 2) Perform a backend fix :-** 
 Am working on an RCA for the same. It seems difficult to perform under the discussed constraints.

**Priority 3) Make this fix to adhere to the standards.**

**Pull request closed without merging**
