### PR TITLE
RA-1592 : Boostrap as a foundation for Reference Application UI Project. 

### PR DESCRIPTION
**Pull request by Akayeshmantha**
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now

1.Media queries for home page.
2. New sass file for home.gsp page.
3.date ranger css fix.
4. Home page adding responsiveness.
5.Adding responsiveness for appointment type table.
6.schedule provider css fixes. 

This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592

### CODE REVIEW

**Comment by HerbertYiga** [comment]
check the failing CI logs

**Comment by mogoodrich** [comment]
I haven't looked in detail, but seems strange that css changes would cause a build failure...

@Akayeshmantha can you give a quick summary of what this change is meant to entail?

**Comment by Akayeshmantha** [comment]
Hi @mogoodrich  seems like the build issue was there in previous PR's as well.The same issue cannot do bower install.

There is a ticket to fix this issue as well.But seems like it is not fixed yet.
https://github.com/openmrs/openmrs-module-appointmentschedulingui/pull/8

**Comment by mogoodrich** [comment]
@Akayeshmantha sounds good, I am okay with meging without the fix and confirming the build works in CI, at least for now...

Can you quickly summary what the CSS changes are meant to do for me?

**Comment by jwnasambu** [comment]
@ayesh did you see the above comment?

**Comment by Akayeshmantha** [comment]
Hi @jwnasambu  yes the build issue was there in previous PR's as well.The same issue cannot do bower install.

There is a ticket to fix this issue as well.But seems like it is not fixed yet.
#8

I opened a PR and it did't do the workaround as supposed as well.Still we have the issue on this.

**Comment by jwnasambu** [comment]
@ayesh it the css summary that am referring to.

**Comment by Akayeshmantha** [comment]
@jwnasambu  I have added the summary in the description.

**Comment by ssmusoke** [comment]
@jwnasambu @mogoodrich Can I go ahead and merge this?

**Comment by Akayeshmantha** [comment]
@mogoodrich  @ssmusoke  now the build is back to normal

**Pull request merged**
